# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1c0t_ubNzo7xo-CqnKJ5C18q89gZTlZ

ClinicalTrials.gov Drug Name Extractor with Synonym Deduplication
=================================================================
Fetches all interventional trials from ClinicalTrials.gov v2 API,
extracts drug intervention names and their synonyms, and deduplicates
using Union-Find for transitive synonym resolution.

Designed to run in Google Colab.

DATA SOURCES (ClinicalTrials.gov v2 API fields):
─────────────────────────────────────────────────
We extract drug names from TWO sections of the study JSON:

1. STUDY-SUBMITTED DATA (protocolSection.armsInterventionsModule.interventions)
   Each intervention object has:
   ├── name        (str)       — Primary intervention name (e.g., "Pembrolizumab")
   ├── type        (enum)      — DRUG, BIOLOGICAL, PROCEDURE, DEVICE, etc.
   ├── otherNames  (list[str]) — Sponsor-provided synonyms/aliases
   ├── description (str)       — Free-text description (not used for names)
   └── armGroupLabels (list)   — Arm assignments (not used)

   We filter: type IN ('DRUG', 'BIOLOGICAL'), skip placebos.

2. NLM-DERIVED MESH TERMS (derivedSection.interventionBrowseModule)
   NLM automatically maps interventions to standardized MeSH vocabulary:
   ├── meshes[]
   │   ├── id   (str) — MeSH unique identifier
   │   └── term (str) — Standardized MeSH term (e.g., "Metformin")
   └── browseLeaves[]
       ├── id        (str) — Leaf identifier
       ├── name      (str) — MeSH concept name
       ├── asFound   (str) — Original text that matched to this concept
       └── relevance (str) — "LOW" or "HIGH"

   We use HIGH-relevance browseLeaves to link study-submitted names
   to their NLM-standardized MeSH equivalents, creating additional
   synonym edges for the Union-Find.

DEDUPLICATION ALGORITHM:
─────────────────────────
Union-Find (Disjoint Set Union) with path compression and union by rank.
Handles transitive synonyms:
  - Trial 1: "BI 5005" has otherName "ABC"
  - Trial 2: "TH 5005" has otherName "ZWX"
  - Trial 3: "ZWX" has otherName "ABC"
  → All four names (BI 5005, TH 5005, ABC, ZWX) merge into one group.

Usage:
    from ctgov_drug_names_extractor import fetch_and_deduplicate_drugs
    df, drugs_json = fetch_and_deduplicate_drugs(max_pages=5)   # quick test
    df, drugs_json = fetch_and_deduplicate_drugs()               # ALL trials
"""

!pip install -q "gliner[tokenizers]"

from transformers import pipeline
from gliner import GLiNER

# Load the model and tokenizer
# Model: https://huggingface.co/OpenMed/OpenMed-ZeroShot-NER-Pharma-XLarge-770M
model_name = "OpenMed/OpenMed-ZeroShot-NER-Pharma-XLarge-770M"


g_model = GLiNER.from_pretrained(model_name)

import requests
import json
import csv
import time
import pandas as pd
from collections import defaultdict
from pathlib import Path
from typing import Optional

# =============================================================================
# 1. UNION-FIND DATA STRUCTURE
# =============================================================================

class UnionFind:
    """
    Union-Find (Disjoint Set Union) with path compression and union by rank.
    Earlier-seen names become canonical representatives.
    All matching is case-insensitive, but original casing is preserved.
    """

    def __init__(self):
        self.parent = {}       # normalized_name -> normalized_parent
        self.rank = {}         # normalized_name -> rank
        self.original = {}     # normalized_name -> first-seen original casing
        self.first_seen = {}   # normalized_name -> insertion order
        self._counter = 0

    @staticmethod
    def _normalize(name: str) -> str:
        return name.strip().lower()

    def add(self, name: str):
        """Add a name if not already present."""
        norm = self._normalize(name)
        if norm not in self.parent:
            self.parent[norm] = norm
            self.rank[norm] = 0
            self.original[norm] = name.strip()
            self.first_seen[norm] = self._counter
            self._counter += 1

    def find(self, name: str) -> str:
        """Find root representative (with path compression)."""
        norm = self._normalize(name)
        if norm not in self.parent:
            self.add(name)
        return self._find_norm(norm)

    def _find_norm(self, norm: str) -> str:
        """Find root for already-normalized key (path compression)."""
        if self.parent[norm] != norm:
            self.parent[norm] = self._find_norm(self.parent[norm])
        return self.parent[norm]

    def union(self, name_a: str, name_b: str):
        """Merge two sets. Earlier-seen name becomes root."""
        root_a = self.find(name_a)
        root_b = self.find(name_b)
        if root_a == root_b:
            return

        # Union by rank, preferring earlier-seen as root
        if self.rank[root_a] < self.rank[root_b]:
            root_a, root_b = root_b, root_a
        if self.first_seen[root_b] < self.first_seen[root_a]:
            root_a, root_b = root_b, root_a
            if self.rank[root_a] == self.rank[root_b]:
                self.rank[root_a] += 1

        self.parent[root_b] = root_a
        if self.rank[root_a] == self.rank[root_b]:
            self.rank[root_a] += 1

    def get_groups(self) -> dict:
        """Returns {canonical_name: sorted list of all names in group}."""
        groups = defaultdict(set)
        for norm in self.parent:
            root = self._find_norm(norm)
            groups[root].add(self.original[norm])

        return {
            self.original[root_norm]: sorted(members, key=lambda x: x.lower())
            for root_norm, members in groups.items()
        }

# =============================================================================
# 2. CONSTANTS AND HELPERS
# =============================================================================

API_BASE = "https://clinicaltrials.gov/api/v2/studies"

# Fields to request from the API — kept minimal for speed
# Source 1: Study-submitted intervention data (name, type, otherNames)
# Source 2: NLM-derived MeSH terms (standardized drug vocabulary)
API_FIELDS = [
    "protocolSection.identificationModule.nctId",
    "protocolSection.armsInterventionsModule.interventions",
    "derivedSection.interventionBrowseModule",
]

DRUG_TYPES = {"DRUG", "BIOLOGICAL"}

PLACEBO_KEYWORDS = {"placebo", "placebos", "sham", "placebo comparator"}


def is_placebo(name: str) -> bool:
    """Check if an intervention name is a placebo/sham."""
    name_lower = name.strip().lower()
    if name_lower in PLACEBO_KEYWORDS:
        return True
    if "placebo" in name_lower or "sham" in name_lower:
        return True
    return False

# =============================================================================
# 3. API INTERACTION FUNCTIONS
# =============================================================================

def build_api_params(
    page_size: int = 1000,
    status_filter: Optional[list] = None,
) -> dict:
    """
    Build query parameters for the ClinicalTrials.gov v2 API.

    Args:
        page_size: Number of studies per page (max 1000).
        status_filter: Optional list of statuses (e.g., ['RECRUITING']).

    Returns:
        Dict of query parameters.
    """
    params = {
        "format": "json",
        "pageSize": page_size,
        "fields": "|".join(API_FIELDS),
        "filter.advanced": "AREA[StudyType]INTERVENTIONAL",
    }
    if status_filter:
        params["filter.overallStatus"] = "|".join(status_filter)
    return params


def fetch_page(
    params: dict,
    page_token: Optional[str] = None,
    max_retries: int = 5,
    verbose: bool = True,
) -> dict:
    """
    Fetch a single page of studies from the CT.gov v2 API with retry logic.

    Args:
        params: Base query parameters from build_api_params().
        page_token: Pagination token for the next page (None for first page).
        max_retries: Number of retries on failure.
        verbose: Print retry/error messages.

    Returns:
        Parsed JSON response dict.

    Raises:
        RuntimeError: If all retries are exhausted.
    """
    request_params = dict(params)
    if page_token:
        request_params["pageToken"] = page_token
    elif "pageToken" in request_params:
        del request_params["pageToken"]

    for attempt in range(max_retries):
        try:
            resp = requests.get(API_BASE, params=request_params, timeout=60)
            if resp.status_code == 429:
                wait = 2 ** (attempt + 1)
                if verbose:
                    print(f"  Rate limited. Waiting {wait}s...")
                time.sleep(wait)
                continue
            resp.raise_for_status()
            return resp.json()
        except requests.exceptions.RequestException as e:
            if attempt < max_retries - 1:
                wait = 2 ** (attempt + 1)
                if verbose:
                    print(f"  Request error: {e}. Retrying in {wait}s...")
                time.sleep(wait)
            else:
                raise RuntimeError(f"Failed after {max_retries} attempts: {e}")

# =============================================================================
# 4. EXTRACTION FUNCTIONS — Parse drug names from API response
# =============================================================================

def extract_interventions_from_study(study: dict) -> list:
    """
    Extract drug/biological interventions from a single study.

    SOURCE FIELD: protocolSection.armsInterventionsModule.interventions[]
    Uses:
        - interventions[].name       → primary drug name
        - interventions[].type       → filter DRUG/BIOLOGICAL only
        - interventions[].otherNames → sponsor-provided synonyms/aliases

    Args:
        study: A single study dict from the CT.gov API response.

    Returns:
        List of dicts: [{"name": str, "other_names": [str], "nct_id": str}]
    """
    protocol = study.get("protocolSection", {})
    nct_id = protocol.get("identificationModule", {}).get("nctId", "UNKNOWN")
    arms_module = protocol.get("armsInterventionsModule", {})
    interventions = arms_module.get("interventions", [])

    results = []
    for intv in interventions:
        intv_type = intv.get("type", "").upper()
        intv_name = intv.get("name", "").strip()
        other_names = intv.get("otherNames", [])

        # Only DRUG and BIOLOGICAL types
        if intv_type not in DRUG_TYPES:
            continue

        # Skip placebo interventions
        if not intv_name or is_placebo(intv_name):
            continue

        # Clean synonyms — remove empty strings and placebos
        clean_others = [
            n.strip() for n in other_names
            if n.strip() and not is_placebo(n)
        ]

        results.append({
            "name": intv_name,
            "other_names": clean_others,
            "nct_id": nct_id,
        })

    return results


def extract_mesh_synonym_pairs(study: dict) -> list:
    """
    Extract NLM-derived MeSH synonym pairs from a study's derived section.

    SOURCE FIELD: derivedSection.interventionBrowseModule
    Uses:
        - browseLeaves[].name     → MeSH concept name (standardized)
        - browseLeaves[].asFound  → Original text that matched (study-submitted)
        - browseLeaves[].relevance→ "HIGH" or "LOW" (we only use HIGH)

    This gives us pairs like:
        ("Metformin Hydrochloride", "Metformin") — asFound ↔ MeSH name
    which creates additional synonym edges for the Union-Find.

    Args:
        study: A single study dict from the CT.gov API response.

    Returns:
        List of tuples: [(original_text, mesh_term), ...]
    """
    derived = study.get("derivedSection", {})
    browse_module = derived.get("interventionBrowseModule", {})
    browse_leaves = browse_module.get("browseLeaves", [])

    pairs = []
    for leaf in browse_leaves:
        relevance = leaf.get("relevance", "").upper()
        if relevance != "HIGH":
            continue

        mesh_name = leaf.get("name", "").strip()
        as_found = leaf.get("asFound", "").strip()

        if mesh_name and as_found and mesh_name.lower() != as_found.lower():
            # Don't create pairs for non-drug MeSH terms
            if not is_placebo(mesh_name) and not is_placebo(as_found):
                pairs.append((as_found, mesh_name))

    return pairs

# =============================================================================
# 4.1. EXTRACT DRUG NAME — Parse druG canonical name and apply Gliner to extract
# =============================================================================

def merge_by_extracted_drugs(df: pd.DataFrame, verbose: bool = True) -> pd.DataFrame:
    """
    Second-pass deduplication:
    1. Group rows sharing the same drug_extracted value
    2. Use the extracted drug name as the new canonical
    3. Merge all their synonyms and nct_ids
    """
    from collections import defaultdict

    # Build groups: extracted_drug (lowered) -> list of row indices
    extract_groups = defaultdict(list)

    # Step 1: Collect rows with exactly 1 extracted drug
    for i, row in df.iterrows():
        if len(row["drug_extracted"]) != 1:
            continue
        drug = row["drug_extracted"][0].strip().lower()
        extract_groups[drug].append(i)

    # Step 2: Also pull in rows whose canonical_name matches an extracted drug
    for drug_key in list(extract_groups.keys()):
        for i, row in df.iterrows():
            if i not in extract_groups[drug_key] and row["canonical_name"].strip().lower() == drug_key:
                extract_groups[drug_key].append(i)

    # Only care about groups with 2+ rows
    merge_groups = {k: list(dict.fromkeys(v)) for k, v in extract_groups.items() if len(set(v)) > 1}

    if verbose:
        print(f"  GLiNER merge: {len(merge_groups)} extracted drugs match multiple rows")

    if not merge_groups:
        return df

    # Track which rows have been consumed
    already_merged = set()
    rows_to_drop = []

    for extracted_drug, indices in merge_groups.items():
        # Skip if all indices already merged
        indices = [i for i in indices if i not in already_merged]
        if len(indices) < 2:
            continue

        # Find the canonical casing of the extracted drug
        # Prefer an index whose canonical_name exactly matches the extracted drug
        anchor_idx = None
        for i in indices:
            if df.at[i, "canonical_name"].strip().lower() == extracted_drug:
                anchor_idx = i
                break
        if anchor_idx is None:
            anchor_idx = indices[0]

        # Merge all rows into anchor
        combined_syns = []
        combined_ncts = []
        seen = set()

        for i in indices:
            for s, n in zip(df.at[i, "synonyms"], df.at[i, "nct_ids"]):
                if s.lower() not in seen:
                    seen.add(s.lower())
                    combined_syns.append(s)
                    combined_ncts.append(n)

        # Set the extracted drug as canonical name
        # Find original casing from the data
        canonical = df.at[indices[0], "drug_extracted"][0]

        df.at[anchor_idx, "canonical_name"] = canonical
        df.at[anchor_idx, "synonyms"] = combined_syns
        df.at[anchor_idx, "nct_ids"] = combined_ncts
        df.at[anchor_idx, "synonym_count"] = len(combined_syns)

        # Mark others for removal
        for i in indices:
            if i != anchor_idx:
                rows_to_drop.append(i)
                already_merged.add(i)

    df = df.drop(rows_to_drop).reset_index(drop=True)

    # Refresh display columns
    df["synonyms_display"] = df["synonyms"].apply(lambda x: " | ".join(x))
    df["nct_ids_display"] = df["nct_ids"].apply(lambda x: " | ".join(x))

    if verbose:
        print(f"  Dropped {len(rows_to_drop)} rows after merging")
        print(f"  Remaining: {len(df)} unique drug entities")

    return df

# =============================================================================
# 4.2. MERGE BY SUBSET DRUG — If all the synonyms is superset of drug extracted
# =============================================================================

def merge_by_subset_drugs(df: pd.DataFrame, verbose: bool = True) -> pd.DataFrame:
    """
    Third-pass deduplication:
    For rows with drug_extracted length > 1, check if ALL extracted names
    are a subset of another row's synonyms. If so, merge them.
    Canonical name = shorter name (fewer characters).
    """
    from collections import defaultdict

    # Build synonym lookup: lowered synonym -> list of row indices
    syn_to_rows = defaultdict(set)
    for i, row in df.iterrows():
        for s in row["synonyms"]:
            syn_to_rows[s.strip().lower()].add(i)

    rows_to_drop = []
    already_merged = set()

    for i, row in df.iterrows():
        if i in already_merged:
            continue
        if len(row["drug_extracted"]) <= 1:
            continue

        extracted_lower = [d.strip().lower() for d in row["drug_extracted"]]

        # Find rows that contain ALL extracted drugs in their synonyms
        candidate_sets = [syn_to_rows.get(d, set()) for d in extracted_lower]
        if not candidate_sets:
            continue

        # Intersect: rows that have every extracted drug in synonyms
        common_rows = candidate_sets[0].copy()
        for s in candidate_sets[1:]:
            common_rows &= s

        # Remove self
        common_rows.discard(i)
        # Remove already merged
        common_rows -= already_merged

        if not common_rows:
            continue

        # Pick the best target: prefer the one whose canonical is shortest
        target_idx = min(common_rows, key=lambda x: len(df.at[x, "canonical_name"]))

        # Decide canonical: shorter name wins
        src_canonical = df.at[i, "canonical_name"]
        tgt_canonical = df.at[target_idx, "canonical_name"]
        new_canonical = src_canonical if len(src_canonical) < len(tgt_canonical) else tgt_canonical

        # Merge synonyms + nct_ids
        combined_syns = []
        combined_ncts = []
        seen = set()

        for idx in [target_idx, i]:
            for s, n in zip(df.at[idx, "synonyms"], df.at[idx, "nct_ids"]):
                if s.lower() not in seen:
                    seen.add(s.lower())
                    combined_syns.append(s)
                    combined_ncts.append(n)

        df.at[target_idx, "canonical_name"] = new_canonical
        df.at[target_idx, "synonyms"] = combined_syns
        df.at[target_idx, "nct_ids"] = combined_ncts
        df.at[target_idx, "synonym_count"] = len(combined_syns)

        rows_to_drop.append(i)
        already_merged.add(i)

    df = df.drop(rows_to_drop).reset_index(drop=True)

    # Refresh display columns
    df["synonyms_display"] = df["synonyms"].apply(lambda x: " | ".join(x))
    df["nct_ids_display"] = df["nct_ids"].apply(lambda x: " | ".join(x))

    if verbose:
        print(f"  Subset merge: dropped {len(rows_to_drop)} rows")
        print(f"  Remaining: {len(df)} unique drug entities")

    return df

# =============================================================================
# 5. MAIN FETCH LOOP
# =============================================================================

def fetch_all_interventional_drugs(
    max_pages: Optional[int] = None,
    page_size: int = 1000,
    status_filter: Optional[list] = None,
    include_mesh: bool = True,
    verbose: bool = True,
) -> tuple:
    """
    Fetch all drug interventions from ClinicalTrials.gov v2 API.

    Iterates through all pages, extracting:
    1. Study-submitted drug names + otherNames (from protocolSection)
    2. NLM-derived MeSH synonym pairs (from derivedSection)

    Args:
        max_pages: Max pages to fetch (None = all). Each page ≈ 1000 studies.
        page_size: Studies per API call (max 1000).
        status_filter: Optional list of statuses e.g. ['RECRUITING'].
        include_mesh: Also extract MeSH-derived synonym pairs.
        verbose: Print progress.

    Returns:
        (interventions, mesh_pairs):
            - interventions: list of {"name", "other_names", "nct_id"} dicts
            - mesh_pairs: list of (original_text, mesh_term) tuples
    """
    all_interventions = []
    all_mesh_pairs = []
    page_token = None
    page_num = 0
    total_studies = 0

    params = build_api_params(page_size, status_filter)

    if verbose:
        print("=" * 70)
        print("ClinicalTrials.gov Drug Name Extractor")
        print("=" * 70)
        print(f"Fetching interventional trials (page_size={page_size})...")
        print(f"Fields requested:")
        for f in API_FIELDS:
            print(f"  • {f}")
        print()

    while True:
        if max_pages is not None and page_num >= max_pages:
            if verbose:
                print(f"\nReached max_pages limit ({max_pages}). Stopping.")
            break

        data = fetch_page(params, page_token, verbose=verbose)
        studies = data.get("studies", [])
        total_studies += len(studies)
        page_num += 1

        # Extract from each study
        for study in studies:
            # Source 1: Study-submitted interventions (name + otherNames)
            study_drugs = extract_interventions_from_study(study)
            all_interventions.extend(study_drugs)

            # Source 2: NLM-derived MeSH synonym pairs
            if include_mesh:
                mesh_pairs = extract_mesh_synonym_pairs(study)
                all_mesh_pairs.extend(mesh_pairs)

        if verbose:
            total_count = data.get("totalCount", "?")
            print(
                f"  Page {page_num}: {len(studies)} studies | "
                f"Total: {total_studies} | "
                f"API total: {total_count} | "
                f"Drugs: {len(all_interventions)} | "
                f"MeSH pairs: {len(all_mesh_pairs)}"
            )

        # Next page
        page_token = data.get("nextPageToken")
        if not page_token:
            if verbose:
                print(f"\nDone! Fetched {total_studies} studies across {page_num} pages.")
            break

        time.sleep(0.3)  # Be respectful to the API

    return all_interventions, all_mesh_pairs

from collections import defaultdict

def deduplicate_drugs(
    interventions: list,
    mesh_pairs: Optional[list] = None,
    verbose: bool = True,
    trace_drug: Optional[str] = None,
) -> dict:

  groups_raw = defaultdict(dict)  # key -> {normalized_name: (original_name, nct_id)}

  for intv in interventions:
      key = intv["name"].strip().lower()
      name = intv["name"].strip()
      nct_id = intv["nct_id"]

      if key not in groups_raw[key]:
          groups_raw[key][key] = (name, nct_id)

      for syn in intv["other_names"]:
          syn_clean = syn.strip()
          syn_norm = syn_clean.lower()
          if syn_norm not in groups_raw[key]:
              groups_raw[key][syn_norm] = (syn_clean, nct_id)

      # Print drug traces
      if trace_drug and trace_drug.lower() == key:
          print(
              f"  [TRACE] NCT={intv['nct_id']} | "
              f"name='{intv['name']}' | "
              f"otherNames={intv['other_names']} | "
              f"group_so_far={groups_raw[key]}"
          )


  groups = {}
  for key, name_nct_map in groups_raw.items():
      sorted_items = sorted(name_nct_map.values(), key=lambda x: x[0].lower())
      canonical = next((orig for orig, _ in sorted_items if orig.lower() == key), sorted_items[0][0])

      groups[canonical] = {
          "synonyms": [orig for orig, _ in sorted_items],
          "nct_ids": [nct for _, nct in sorted_items],
      }

  return groups

# =============================================================================
# 7. OUTPUT FUNCTIONS — Save results to JSON and CSV
# =============================================================================

def groups_to_records(groups: dict) -> list:
    """
    Convert groups dict to a sorted list of record dicts.

    Args:
        groups: {canonical_name: [synonyms]} from deduplicate_drugs().

    Returns:
        Sorted list of {"canonical_name", "synonyms", "synonym_count"} dicts.
    """
    return sorted(
    [
        {
            "canonical_name": canonical,
            "synonyms": data["synonyms"],
            "nct_ids": data["nct_ids"],
            "synonym_count": len(data["synonyms"]),
        }
        for canonical, data in groups.items()
    ],
    key=lambda x: x["canonical_name"].lower(),
)


def save_json(records: list, filepath: str) -> str:
    """Save records to JSON file. Returns the filepath."""
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(records, f, indent=2, ensure_ascii=False)
    return str(path)


def save_csv(records: list, filepath: str) -> str:
    """Save records to CSV file (synonyms pipe-separated). Returns filepath."""
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["canonical_name", "synonyms", "synonym_count"])
        for drug in records:
            writer.writerow([
                drug["canonical_name"],
                " | ".join(drug["synonyms"]),
                drug["synonym_count"],
            ])
    return str(path)


def save_results(
    groups: dict,
    output_dir: str = ".",
    json_filename: str = "ctgov_drugs.json",
    csv_filename: str = "ctgov_drugs.csv",
    verbose: bool = True,
) -> tuple:
    """
    Save deduplicated drugs to JSON and CSV.

    Returns:
        (json_path, csv_path, records)
    """
    records = groups_to_records(groups)

    json_path = save_json(records, str(Path(output_dir) / json_filename))
    csv_path = save_csv(records, str(Path(output_dir) / csv_filename))

    if verbose:
        print(f"\nSaved {len(records)} unique drug entities:")
        print(f"  JSON: {json_path}")
        print(f"  CSV:  {csv_path}")

    return json_path, csv_path, records


def create_dataframe(records: list) -> pd.DataFrame:
    """
    Create a pandas DataFrame from records with a display-friendly synonyms column.

    Args:
        records: List of dicts from groups_to_records().

    Returns:
        DataFrame with columns: canonical_name, synonyms, synonym_count, synonyms_display
    """
    df = pd.DataFrame(records)
    if not df.empty:
        df["nct_ids_display"] = df["nct_ids"].apply(lambda x: " | ".join(x))
    return df


def print_summary(df: pd.DataFrame, elapsed: float):
    """Print a summary of the extraction results."""
    if df.empty:
        print("No drugs found.")
        return

    print(f"\n{'=' * 70}")
    print(f"COMPLETE in {elapsed:.1f}s ({elapsed / 60:.1f} min)")
    print(f"  Unique drug entities: {len(df)}")
    print(f"  Total name variants:  {df['synonym_count'].sum()}")
    print(f"  Avg synonyms/drug:    {df['synonym_count'].mean():.1f}")
    print(f"  Max synonyms:         {df['synonym_count'].max()}")

    top5 = df.nlargest(5, "synonym_count")[["canonical_name", "synonym_count"]]
    print(f"\n  Top 5 drugs by synonym count:")
    for _, row in top5.iterrows():
        print(f"    {row['canonical_name']}: {row['synonym_count']} synonyms")
    print(f"{'=' * 70}")


def download_in_colab(json_path: str, csv_path: str, verbose: bool = True):
    """Attempt to auto-download files if running in Google Colab."""
    try:
        from google.colab import files as colab_files
        if verbose:
            print("\nDownloading files to your local machine...")
        colab_files.download(json_path)
        colab_files.download(csv_path)
    except ImportError:
        pass  # Not in Colab

def extract_drug_names(df: pd.DataFrame, g_model, labels: list = None,
                       batch_size: int = 256, verbose: bool = True) -> pd.DataFrame:
    if labels is None:
        labels = ["CHE"]

    # Split into single-word (skip) vs multi-word (process)
    multi_word_mask = df["canonical_name"].str.strip().str.split().str.len() > 1
    multi_word_texts = df.loc[multi_word_mask, "canonical_name"].tolist()

    if verbose:
        print(f"  Skipping {(~multi_word_mask).sum()} single-word names")
        print(f"  Processing {len(multi_word_texts)} multi-word names in batches of {batch_size}")

    # Batch predict
    all_entities = []
    for i in range(0, len(multi_word_texts), batch_size):
        batch = multi_word_texts[i:i + batch_size]
        batch_results = g_model.inference (
            batch, labels, flat_ner=True, threshold=0.5
        )
        all_entities.extend(batch_results)

        if verbose:
            print(f"  Batch {i // batch_size + 1}: {min(i + batch_size, len(multi_word_texts))}/{len(multi_word_texts)}")

    # Map results back
    extracted = [[] for _ in range(len(df))]
    multi_indices = df.index[multi_word_mask].tolist()
    for idx, entities in zip(multi_indices, all_entities):
        if entities:
            extracted[idx] = list(dict.fromkeys(e["text"] for e in entities))

    df["drug_extracted"] = extracted
    df["drug_extracted_display"] = df["drug_extracted"].apply(lambda x: " | ".join(x))
    return df

# =============================================================================
# 8. MAIN PIPELINE — Single call to do everything
# =============================================================================

def fetch_and_deduplicate_drugs(
    max_pages: Optional[int] = None,
    page_size: int = 1000,
    status_filter: Optional[list] = None,
    include_mesh: bool = True,
    g_model=None,              # ← add
    gliner_batch_size: int = 256,  # ← add
    output_dir: str = ".",
    json_filename: str = "ctgov_drugs.json",
    csv_filename: str = "ctgov_drugs.csv",
    trace_drug: Optional[str] = None,
    verbose: bool = True,
) -> tuple:
    """
    End-to-end pipeline: Fetch → Extract → Deduplicate → Save.

    Data sources extracted per study:
    ─────────────────────────────────
    1. protocolSection.armsInterventionsModule.interventions[]
       ├── .name       → Primary drug name
       ├── .type       → Filter: DRUG or BIOLOGICAL only
       └── .otherNames → Sponsor-provided synonyms
    2. derivedSection.interventionBrowseModule.browseLeaves[]
       ├── .asFound    → Original text from study
       ├── .name       → NLM-standardized MeSH term
       └── .relevance  → Only HIGH relevance used

    Args:
        max_pages: Max API pages to fetch (None = ALL trials).
                   Use max_pages=5 for quick testing (~5000 studies).
        page_size: Studies per API page (max 1000).
        status_filter: Optional list like ['RECRUITING', 'COMPLETED'].
        include_mesh: Include NLM-derived MeSH synonyms (recommended).
        output_dir: Where to save output files.
        json_filename: Name for JSON output.
        csv_filename: Name for CSV output.
        verbose: Print progress updates.

    Returns:
        (df, drugs_list):
            - df: pandas DataFrame [canonical_name, synonyms, synonym_count, synonyms_display]
            - drugs_list: list of dicts (same as saved JSON)

    Example (Google Colab):
        # Quick test (~5000 studies):
        df, drugs = fetch_and_deduplicate_drugs(max_pages=5)

        # Full extraction (all trials, 15-30+ min):
        df, drugs = fetch_and_deduplicate_drugs()

        # Only recruiting trials:
        df, drugs = fetch_and_deduplicate_drugs(status_filter=['RECRUITING'])

        # Without MeSH synonyms (faster, fewer synonyms):
        df, drugs = fetch_and_deduplicate_drugs(include_mesh=False)
    """
    start_time = time.time()

    # Step 1: Fetch all interventions and MeSH pairs
    interventions, mesh_pairs = fetch_all_interventional_drugs(
        max_pages=max_pages,
        page_size=page_size,
        status_filter=status_filter,
        include_mesh=include_mesh,
        verbose=verbose,
    )

    if not interventions:
        print("No interventions found!")
        return pd.DataFrame(), []

    # Step 2: Deduplicate with Union-Find
    groups = deduplicate_drugs(
    interventions,
    mesh_pairs=mesh_pairs if include_mesh else None,
    verbose=verbose,
    trace_drug=trace_drug,
)

    # Step 3: Save to files
    json_path, csv_path, records = save_results(
        groups,
        output_dir=output_dir,
        json_filename=json_filename,
        csv_filename=csv_filename,
        verbose=verbose,
    )

    # Step 4: Create DataFrame
    df = create_dataframe(records)

    # Step 4b: GLiNER extraction + second-pass merge
    if g_model is not None:
        if verbose:
            print("\nRunning GLiNER drug name extraction...")
        df = extract_drug_names(df, g_model, batch_size=gliner_batch_size, verbose=verbose)

        if verbose:
            print("Merging by extracted drug names (exact match)...")
        df = merge_by_extracted_drugs(df, verbose=verbose)

        if verbose:
            print("Merging by subset drug names...")
        df = merge_by_subset_drugs(df, verbose=verbose)

    # Step 5: Summary
    elapsed = time.time() - start_time
    if verbose:
        print_summary(df, elapsed)

    # Step 6: Auto-download in Colab
    download_in_colab(json_path, csv_path, verbose=verbose)

    return df, records

# =============================================================================
# 9. STANDALONE EXECUTION
# =============================================================================

# df, drugs = fetch_and_deduplicate_drugs(max_pages=5, trace_drug="Agonist")
df, drugs = fetch_and_deduplicate_drugs(
    max_pages=5,
    g_model=g_model,
    trace_drug="Agonist",
    gliner_batch_size=512,
)
print(f"\nSample output (first 10 rows):")
print(df[["canonical_name", "synonym_count", "nct_ids_display"]].head(10).to_string())

import json

with open("ctgov_drugs.json", "r", encoding="utf-8") as f:
    data = json.load(f)

rituximab_drugs = [
    drug for drug in data
    if drug.get("canonical_name", "").lower() == "rituximab"
]

print(json.dumps(rituximab_drugs, indent=2))

mask = (
    df['canonical_name'].str.contains('rituxan', case=False, na=False) |
    df['synonyms_display'].str.contains('rituxan', case=False, na=False)
)
matches = df[mask]

print(set(matches['synonyms_display']))

# df[df.canonical_name.str.contains('Alcohol')]
df.iloc[200:400,:]

df = extract_drug_names(df, g_model, labels=["CHE"], verbose = True)

df_duplicate = (
    df[
        df["drug_extracted"].apply(lambda x: isinstance(x, list) and len(x) > 0)
        & df.duplicated(subset="drug_extracted", keep=False)
    ]
    .sort_values(by="drug_extracted")
    .reset_index(drop=True)
)

df_duplicate